// Ensure the categories are properly alphabetized
export const serviceCategories = [
  { value: "basement", label: "Basement" },
  { value: "bathroom", label: "Bathroom" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "concrete", label: "Concrete" },
  { value: "deck-patio", label: "Deck & Patio" },
  { value: "drywall", label: "Drywall" },
  { value: "electrical", label: "Electrical" },
  { value: "fencing", label: "Fencing" },
  { value: "flooring", label: "Flooring" },
  { value: "garage", label: "Garage & Driveway" },
  { value: "gutter-work", label: "Gutter Work" },
  { value: "handyman", label: "Handyman Services" },
  { value: "hvac", label: "HVAC" },
  { value: "insulation", label: "Insulation" },
  { value: "kitchen", label: "Kitchen" },
  { value: "landscaping", label: "Landscaping" },
  { value: "other", label: "Other" },
  { value: "outdoor", label: "Other Outdoor" },
  { value: "painting", label: "Painting" },
  { value: "plumbing", label: "Plumbing" },
  { value: "pressure-washing", label: "Pressure Washing" },
  { value: "roofing", label: "Roofing" },
  { value: "siding", label: "Siding" },
  { value: "tree-service", label: "Tree Service" },
  { value: "windows-doors", label: "Windows & Doors" },
]
